/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "pmbpawntaislortnjzmq"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtYnBhd250YWlzbG9ydG5qem1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI2NTYyMjcsImV4cCI6MjA4ODIzMjIyN30.Rb_dqcnicLoKqL5YdTLi7RwqX8yAgijdXhqJ--YQH0c"